<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup Label="Analysis">
        <AnalysisModeNaming>Recommended</AnalysisModeNaming>
        <AnalysisModeSecurity>Recommended</AnalysisModeSecurity>
        <AnalysisModeReliability>Recommended</AnalysisModeReliability>
        <AnalysisModeReliability>Recommended</AnalysisModeReliability>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CSharpier.MsBuild" Version="*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="IDisposableAnalyzers" Version="*"/>
    </ItemGroup>
</Project>