using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace CreateDiscovery.Tests;

public class SourceGeneratorWithAttributesTests
{
    private const string VectorClassText = @"
namespace TestNamespace;

[Generators.Report]
public partial class Vector3
{
    public float X { get; set; }
    public float Y { get; set; }
    public float Z { get; set; }
}";

    private const string ExpectedGeneratedClassText = @"// <auto-generated/>

using System;
using System.Collections.Generic;

namespace TestNamespace;

partial class Vector3
{
    public IEnumerable<string> Report()
    {
        yield return $""X:{this.X}"";
        yield return $""Y:{this.Y}"";
        yield return $""Z:{this.Z}"";
    }
}
";
    //
    // [Fact]
    // public void GenerateReportMethod()
    // {
    //     var generator = new SourceGeneratorWithAttributes();
    //
    //     var driver = CSharpGeneratorDriver.Create(generator);
    //
    //     var compilation = CSharpCompilation.Create(nameof(SourceGeneratorWithAdditionalFilesTests),
    //         new[] { CSharpSyntaxTree.ParseText(VectorClassText) },
    //         new[]
    //         {
    //             // To support 'System.Attribute' inheritance, add reference to 'System.Private.CoreLib'.
    //             MetadataReference.CreateFromFile(typeof(object).Assembly.Location)
    //         });
    //
    //
    //     var runResult = driver.RunGenerators(compilation).GetRunResult();
    //
    //
    //     var generatedFileSyntax = runResult.GeneratedTrees.Single(t => t.FilePath.EndsWith("Vector3.g.cs"));
    //
    //
    //     Assert.Equal(ExpectedGeneratedClassText, generatedFileSyntax.GetText().ToString(),
    //         ignoreLineEndingDifferences: true);
    // }
}